In [7]:
import pandas as pd

In [20]:
df_verif = pd.read_csv("./data/ge_events_df.csv")
df_verif.head(5)

,Unnamed: 0,uid,canonicalurl,title_fr,description_fr,longdescription_fr,conditions_fr,timings,daterange_fr,firstdate_begin,...,location_address,location_postalcode,location_city,location_department,location_region,age_min,age_max,registration,event_actif,texte_rag
0,0,29056606,https://openagenda.com/villedecmz/events/conse...,Conseil municipal,Conseil municipal,NaN,NaN,"[{""begin"": ""2024-11-21T18:30:00+01:00"", ""end"":...","21 novembre 2024 - 18 décembre 2025, certains ...",2024-11-21T17:30:00+00:00,...,Place de l'Hôtel de Ville 08000 Charleville-Mé...,08000,Charleville-Mézières,Ardennes,Grand Est,NaN,NaN,NaN,False,Titre: Conseil municipal\nDescription: Conseil...
1,1,90172032,https://openagenda.com/villedecmz/events/conco...,Concours de belote,Concours de belote,<p>Début des jeux 20 h 30</p>,NaN,"[{""begin"": ""2025-02-07T19:30:00+01:00"", ""end"":...","Vendredi 7 février 2025, 19h30",2025-02-07T18:30:00+00:00,...,26 bis rue d'Etion 08000 Charleville-Mézières,08000,Charleville-Mézières,Ardennes,Grand Est,NaN,NaN,"[{""type"": ""phone"", ""value"": ""0601715119""}]",False,Titre: Concours de belote\nDescription: Concou...
2,2,257704,https://openagenda.com/villedecmz/events/tourn...,tournoi de ping-pong,ping-pong,NaN,NaN,"[{""begin"": ""2025-01-25T14:00:00+01:00"", ""end"":...",25 et 26 janvier 2025,2025-01-25T13:00:00+00:00,...,14 chemin du Mémorial 08000 Charleville-Mézières,08000,Charleville-Mézières,Ardennes,Grand Est,NaN,NaN,NaN,False,Titre: tournoi de ping-pong\nDescription: ping...
3,3,20351829,https://openagenda.com/villedecmz/events/porte...,Portes ouvertes l'Atelier,l'Atelier,NaN,entrée libre,"[{""begin"": ""2025-01-18T14:00:00+01:00"", ""end"":...","Samedi 18 janvier 2025, 14h00",2025-01-18T13:00:00+00:00,...,3 C rue Louis Hanot 08000 Charleville-Mézières,08000,Charleville-Mézières,Ardennes,Grand Est,NaN,NaN,NaN,False,Titre: Portes ouvertes l'Atelier\nDescription:...
4,4,54005490,https://openagenda.com/villedecmz/events/apres...,Après-midi dansant,Après-midi dansant,NaN,NaN,"[{""begin"": ""2025-01-12T14:00:00+01:00"", ""end"":...","Dimanche 12 janvier 2025, 14h00",2025-01-12T13:00:00+00:00,...,75 avenue Forest 08000 Charleville-Mézières,08000,Charleville-Mézières,Ardennes,Grand Est,NaN,NaN,"[{""type"": ""link"", ""value"": ""https://www.75fore...",False,Titre: Après-midi dansant\nDescription: Après-...

In [22]:
# récupérer les vraies dates de debut et fin de l'évènement
import json
def extract_first_timing(cell):
    if cell is None:
        return None

    # Si c'est une string JSON → on la charge
    if isinstance(cell, str):
        try:
            timings = json.loads(cell)
        except Exception:
            return None
    else:
        # Si c'est déjà une liste Python
        timings = cell

    # si la liste est vide
    if not timings:
        return None, None

    # On prend la première occurrence
    t0 = timings[0]
    return t0.get("begin")

df_verif["begin"] = df_verif["timings"].apply(extract_first_timing)
df_verif["begin"] = pd.to_datetime(df_verif["begin"], utc=True)

In [23]:
df_verif.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11753 entries, 0 to 11752
Data columns (total 23 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Unnamed: 0           11753 non-null  int64
 1   uid                  11753 non-null  int64
 2   canonicalurl         11753 non-null  object
 3   title_fr             11690 non-null  object
 4   description_fr       11690 non-null  object
 5   longdescription_fr   10289 non-null  object
 6   conditions_fr        5922 non-null   object
 7   timings              11753 non-null  object
 8   daterange_fr         11753 non-null  object
 9   firstdate_begin      11753 non-null  object
 10  lastdate_end         11753 non-null  object
 11  location_name        11753 non-null  object
 12  location_address     11753 non-null  object
 13  location_postalcode  11684 non-null  object
 14  location_city        11739 non-null  object
 15  location_department  11753 non-null  object
 16  location_region      11753 non-null  object
 17  age_min              1394 non-null   float64
 18  age_max              2187 non-null   float64
 19  registration         6309 non-null   object
 20  event_actif          11753 non-null  bool
 21  texte_rag            11753 non-null  object
 22  begin                11753 non-null  datetime64[ns, UTC]
dtypes: bool(1), datetime64[ns, UTC](1), float64(2), int64(2), object(17)
memory usage: 2.0+ MB

In [24]:
print(df_verif["begin"].head(20))

0    2024-11-21 17:30:00+00:00
1    2025-02-07 18:30:00+00:00
2    2025-01-25 13:00:00+00:00
3    2025-01-18 13:00:00+00:00
4    2025-01-12 13:00:00+00:00
5    2025-03-12 13:00:00+00:00
6    2025-02-04 17:00:00+00:00
7    2025-03-15 14:00:00+00:00
8    2025-03-16 14:00:00+00:00
9    2025-02-05 08:30:00+00:00
10   2025-03-21 13:00:00+00:00
11   2025-03-22 09:30:00+00:00
12   2025-02-22 09:15:00+00:00
13   2025-01-31 08:15:00+00:00
14   2025-02-05 08:30:00+00:00
15   2025-01-30 17:30:00+00:00
16   2025-01-08 16:00:00+00:00
17   2025-03-19 09:00:00+00:00
18   2025-01-19 15:30:00+00:00
19   2025-03-23 08:00:00+00:00
Name: begin, dtype: datetime64[ns, UTC]

In [28]:

today = pd.Timestamp.now(tz="UTC")
df_26_actuel = df_verif[(df_verif["begin"].dt.year == 2026) & (df_verif["begin"] >= today)]
df_26_actuel.sort_values(by="begin", ascending=True)

df_stras_concert = df_26_actuel[df_26_actuel['texte_rag'].str.contains('concert|musique', case=False, na=False)]
df_stras_concert

,Unnamed: 0,uid,canonicalurl,title_fr,description_fr,longdescription_fr,conditions_fr,timings,daterange_fr,firstdate_begin,...,location_postalcode,location_city,location_department,location_region,age_min,age_max,registration,event_actif,texte_rag,begin
9538,9538,80023684,https://openagenda.com/office-de-tourisme-de-l...,Tambouille festival,festival itinérant de spectacles et concerts !,<p>Rendez-vous le 6 août à Bult pour le Tambou...,Gratuit,"[{""begin"": ""2026-08-06T09:00:00+02:00"", ""end"":...","Jeudi 6 août, 09h00",2026-08-06T07:00:00+00:00,...,88700,Bult,Vosges,Grand Est,NaN,NaN,"[{""type"": ""link"", ""value"": ""https://tambouille...",True,Titre: Tambouille festival\nDescription: festi...,2026-08-06 07:00:00+00:00
9566,9566,72200779,https://openagenda.com/unidivers-oui-sortir/ev...,Concert de musique classique à Strasbourg – En...,"Événement reporté à une date ultérieure, afin ...",<p>Porté par la devise « La musique fait du bi...,De 20 à 30€ tout public / gratuit moins de 12 ans,"[{""begin"": ""2026-08-14T20:00:00+02:00"", ""end"":...","Vendredi 14 août, 20h00",2026-08-14T18:00:00+00:00,...,67000,Strasbourg,Collectivité européenne d'Alsace,Grand Est,NaN,NaN,"[{""type"": ""link"", ""value"": ""https://musicamefr...",True,Titre: Concert de musique classique à Strasbou...,2026-08-14 18:00:00+00:00
9582,9582,76382570,https://openagenda.com/culture/events/concert-...,Concert au Musée du Cloître,Laissez-vous transporter par un concert au mil...,<p>Laissez-vous transporter par un concert au ...,NaN,"[{""begin"": ""2026-09-19T15:00:00+02:00"", ""end"":...","Samedi 19 septembre, 15h00",2026-09-19T13:00:00+00:00,...,51000,Châlons-en-Champagne,Marne,Grand Est,NaN,NaN,NaN,True,Titre: Concert au Musée du Cloître\nDescriptio...,2026-09-19 13:00:00+00:00
9589,9589,17835202,https://openagenda.com/culture/events/visite-e...,"Visite en musique de l'exposition ""Persistances""",Venez vivre une expérience sensorielle unique....,<p>Venez vivre une expérience sensorielle uniq...,Départ à 16h samedi et dimanche. Réservation c...,"[{""begin"": ""2026-09-19T16:00:00+02:00"", ""end"":...",19 et 20 septembre,2026-09-19T14:00:00+00:00,...,51100,Reims,Marne,Grand Est,NaN,NaN,"[{""type"": ""email"", ""value"": ""reservation@frac-...",True,"Titre: Visite en musique de l'exposition ""Pers...",2026-09-19 14:00:00+00:00
9592,9592,41975895,https://openagenda.com/culture/events/rencontr...,Rencontres musicales et spirituelles,"Pendant une heure, laissez-vous porter par les...","<p>Pendant une heure, laissez-vous porter par ...",NaN,"[{""begin"": ""2026-09-19T18:00:00+02:00"", ""end"":...",19 et 20 septembre,2026-09-19T16:00:00+00:00,...,10000,Troyes,Aube,Grand Est,NaN,NaN,NaN,True,Titre: Rencontres musicales et spirituelles\nD...,2026-09-19 16:00:00+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11637,11637,90575491,https://openagenda.com/bien-grandir-dans-le-sa...,Matinée des Tout-Petits: Pas peur moi !,Animation gratuite à destination des enfants d...,<p>Un espace cocooning et sécurisé est réservé...,Sur inscription,"[{""begin"": ""2026-10-21T09:30:00+02:00"", ""end"":...","Mercredi 21 octobre, 09h30",2026-10-21T07:30:00+00:00,...,57170,Château-Salins,Moselle,Grand Est,NaN,6.0,"[{""type"": ""email"", ""value"": ""rpe@cc-saulnois.f...",True,Titre: Matinée des Tout-Petits: Pas peur moi !...,2026-10-21 07:30:00+00:00
11652,11652,70456613,https://openagenda.com/culture/events/julien-c...,Julien Clerc en concert,Julien Clerc en concert exceptionnel le 10 déc...,"<p>Julien Clerc, c’est plus de 50 ans de tubes...","De 35,00 € à 85,00 €","[{""begin"": ""2026-12-10T20:30:00+01:00"", ""end"":...","Jeudi 10 décembre, 20h30",2026-12-10T19:30:00+00:00,...,52000,Chaumont,Haute-Marne,Grand Est,NaN,NaN,NaN,True,Titre: Julien Clerc en concert\nDescription: J...,2026-12-10 19:30:00+00:00
11676,11676,9850087,https://openagenda.com/rncap/events/rouge-echarpe,Rouge écharpe,Jeune public dès 3 ans,<p>Rouge écharpe raconte l’histoire de l’enfan...,NaN,"[{""begin"": ""2026-12-10T17:00:00+01:00"", ""end"":...","Jeudi 10 décembre, 17h00",2026-12-10T16:00:00+00:00,...,52220,La Porte du Der,Haute-Marne,Grand Est,3.0,99.0,NaN,True,Titre: Rouge écharpe\nDescription: Jeune publi...,2026-12-10 16:00:00+00:00
11714,11714,9828943,https://openagenda.com/culture/events/visite-g...,Visite guidée de la bibliothèque de 10h à 12h ...,Biblis en folie 2026,<p>Découvrez les différents rayons de la bibli...,NaN,"[{""begin"": ""2026-10-03T10:00:00+02:00"", ""end"":...","Samedi 3 octobre, 10h00",2026-10-03T08:00:00+00:00,...,55110,Doulcon,Meuse,Grand Est,NaN,NaN,NaN,True,Titre: Visite guidée de la bibliothèque de 10h...,2026-10-03 08:00:00+00:00
11717,11717,96027626,https://openagenda.com/planlibre/events/projec...,"Projection du film documentaire ""Des chaises e...",**Envirobat Grand Est – ARCAD LQE** et la **Vi...,<p><strong>Envirobat Grand Est – ARCAD LQE</st...,Limité à 50 personnes,"[{""begin"": ""2026-10-14T09:30:00+02:00"", ""end"":...","Mercredi 14 octobre, 09h30",2026-10-14T07:30:00+00:00,...,52000,Chaumont,Haute-Marne,Grand Est,NaN,NaN,"[{""type"": ""link"", ""value"": ""https://www.enviro...",True,"Titre: Projection du film documentaire ""Des ch...",2026-10-14 07:30:00+00:00

In [4]:
df_strasbourg = df_verif[df_verif['location_city'] == 'Strasbourg']
df_strasbourg

,Unnamed: 0,uid,canonicalurl,title_fr,description_fr,longdescription_fr,conditions_fr,timings,daterange_fr,firstdate_begin,...,location_address,location_postalcode,location_city,location_department,location_region,age_min,age_max,registration,event_actif,texte_rag
6,6,79977358,https://openagenda.com/les-evenements-de-la-li...,Rencontre avec Roger Fajnzylberg,Événement gratuit sur inscription via notre si...,<p><strong>Événement gratuit sur inscription</...,NaN,"[{""begin"": ""2025-02-04T18:00:00+01:00"", ""end"":...","Mardi 4 février 2025, 18h00",2025-02-04T17:00:00+00:00,...,"1 rue des Francs Bourgeois,Strasbourg",67000,Strasbourg,Bas-Rhin,Grand Est,NaN,NaN,"[{""type"": ""link"", ""value"": ""https://www.eventb...",False,Titre: Rencontre avec Roger Fajnzylberg\nDescr...
19,19,9596870,https://openagenda.com/unidivers-oui-sortir/ev...,RETRO GAM’IN - STRASBOURG,Evènement RETRO GAM'IN - STRASBOURG 2025 le di...,<p>Ne manquez pas l'Evènement RETRO GAM'IN - S...,sur inscription par mail a partir de 15€ le m ...,"[{""begin"": ""2025-03-23T09:00:00+01:00"", ""end"":...","Dimanche 23 mars 2025, 09h00",2025-03-23T08:00:00+00:00,...,67100,67100,Strasbourg,Bas-Rhin,Grand Est,NaN,99.0,"[{""type"": ""email"", ""value"": ""tandem.events71@g...",False,Titre: RETRO GAM’IN - STRASBOURG\nDescription:...
23,23,64666218,https://openagenda.com/les-evenements-de-la-li...,Rencontre avec Roland Gori,Événement gratuit sur inscription via notre si...,<p><strong>Événement gratuit sur inscription</...,NaN,"[{""begin"": ""2025-03-07T17:30:00+01:00"", ""end"":...","Vendredi 7 mars 2025, 17h30",2025-03-07T16:30:00+00:00,...,"1 rue des Francs Bourgeois,Strasbourg",67000,Strasbourg,Bas-Rhin,Grand Est,NaN,NaN,"[{""type"": ""link"", ""value"": ""https://www.eventb...",False,Titre: Rencontre avec Roland Gori\nDescription...
42,42,36795759,https://openagenda.com/les-evenements-de-la-li...,Rencontre avec Marta Caraion,Événement gratuit sur inscription via notre si...,<p><strong>Événement gratuit sur inscription</...,NaN,"[{""begin"": ""2025-03-04T17:00:00+01:00"", ""end"":...","Mardi 4 mars 2025, 17h00",2025-03-04T16:00:00+00:00,...,"1 rue des Francs Bourgeois,Strasbourg",67000,Strasbourg,Bas-Rhin,Grand Est,NaN,NaN,"[{""type"": ""link"", ""value"": ""https://www.eventb...",False,Titre: Rencontre avec Marta Caraion\nDescripti...
54,54,40996137,https://openagenda.com/les-evenements-de-la-li...,Rencontre avec Marie Nimier,Événement gratuit sur inscription via notre si...,<p><strong>Événement gratuit sur inscription</...,NaN,"[{""begin"": ""2025-02-12T18:00:00+01:00"", ""end"":...","Mercredi 12 février 2025, 18h00",2025-02-12T17:00:00+00:00,...,"1 rue des Francs Bourgeois,Strasbourg",67000,Strasbourg,Bas-Rhin,Grand Est,NaN,NaN,"[{""type"": ""link"", ""value"": ""https://www.eventb...",False,Titre: Rencontre avec Marie Nimier\nDescriptio...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11673,11673,84772811,https://openagenda.com/bicentenaire-photograph...,En quête des photographies d'Alice Bommer,Informations à venir,<p>Informations à venir<br>Le vernissage le 06...,NaN,"[{""begin"": ""2026-11-06T18:00:00+01:00"", ""end"":...",6 novembre - 25 décembre,2026-11-06T17:00:00+00:00,...,"4 Place d'Austerlitz, 67000 Strasbourg, France",67000,Strasbourg,Bas-Rhin,Grand Est,NaN,NaN,NaN,True,Titre: En quête des photographies d'Alice Bomm...
11682,11682,66227214,https://openagenda.com/culture/events/200-sole...,200 soleils : collecte de photographies,Biblis en folie 2026,"<p>Cette année, la photographie fête ses 200 a...",NaN,"[{""begin"": ""2026-10-03T14:00:00+02:00"", ""end"":...","Samedi 3 octobre, 14h00",2026-10-03T12:00:00+00:00,...,"3 Rue Kuhn, 67000 Strasbourg, France",67000,Strasbourg,Bas-Rhin,Grand Est,NaN,NaN,NaN,True,Titre: 200 soleils : collecte de photographies...
11721,11721,36722592,https://openagenda.com/saison-mediterranee-202...,Les Faiseuses. Aller-retour Tunis-Strasbourg 2/2,"Porté par El Warcha, le projet Les Faiseuses a...","<p>Porté par El Warcha, le projet Les Faiseuse...",NaN,"[{""begin"": ""2026-10-21T18:00:00+02:00"", ""end"":...",21 - 24 octobre,2026-10-21T16:00:00+00:00,...,"1, rue de l'Académie 67000 Strasbourg",67000,Strasbourg,Collectivité européenne d'Alsace,Grand Est,NaN,NaN,"[{""type"": ""link"", ""value"": ""https://my.weezeve...",True,Titre: Les Faiseuses. Aller-retour Tunis-Stras...
11725,11725,46629009,https://openagenda.com/panthea/events/thesee-s...,"THÉSÉE, SA VIE NOUVELLE l Valérie Dréville et ...",audiodescription sur casque audio,"<p>Thésée part s’installer à Berlin, la « Vill...",Prix du billet,"[{""begin"": ""2026-10-14T20:30:00+02:00"", ""end"":...","Mercredi 14 octobre, 20h30",2026-10-14T18:30:00+00:00,...,"1 boulevard de Dresde, 67000 Strasbourg",67000,Strasbourg,Collectivité européenne d'Alsace,Grand Est,14.0,99.0,"[{""type"": ""email"", ""value"": ""mathis.bruneteaux...",True,"Titre: THÉSÉE, SA VIE NOUVELLE l Valérie Drévi..."
11730,11730,90089795,https://openagenda.com/bicentenaire-photograph...,Une photographe révélée | Alice Bommer,Texte à venir,"<p>Photographe documentaire et de reportage, A...",NaN,"[{""begin"": ""2026-11-07T14:00:00+01:00"", ""end"":...",7 novembre - 23 décembre,2026-11-07T13:00:00+00:00,...,"4 Place d'Austerlitz, 67000 Strasbourg, France",67000,Strasbourg,Bas-Rhin,Grand Est,NaN,NaN,NaN,True,Titre: Une photographe révélée | Alice Bommer\...

In [ ]:
df_strasbourg_26 =

In [6]:
max(df_verif["firstdate_begin"])

'2026-12-19T14:00:00+00:00'

In [7]:
min(df_verif["firstdate_begin"])

'2025-01-01T18:00:00+00:00'

In [8]:
max(df_verif["lastdate_end"])

'2043-06-04T12:00:00+00:00'

In [ ]:
min(df_verif["lastdate_end"])

'2025-01-04T16:30:00+00:00'

In [11]:
df_verif['location_city'].unique()

<ArrowStringArray>
['Charleville-Mézières',           'Strasbourg',    'Villers-lès-Nancy',
           'Lapoutroie',                'Laxou',               'Colmar',
            'Fellering',    'Sainte-Marguerite',                'Reims',
                'NANCY',
 ...
   'Brienne-la-Vieille',          'Fromelennes',          'Saint-Oulph',
           'Ortoncourt',         'Willgottheim',        'Pierrevillers',
      'Montigny le Roi',             'Distroff',                'Lesse',
     'Bourgogne-Fresne']
Length: 1391, dtype: str