In [7]:
import pandas as pd

In [20]:
df_verif = pd.read_csv("./data/ge_events_df.csv")
df_verif.head(5)

,Unnamed: 0,uid,canonicalurl,title_fr,description_fr,longdescription_fr,conditions_fr,timings,daterange_fr,firstdate_begin,...,location_address,location_postalcode,location_city,location_department,location_region,age_min,age_max,registration,event_actif,texte_rag
0,0,29056606,https://openagenda.com/villedecmz/events/conse...,Conseil municipal,Conseil municipal,NaN,NaN,"[{""begin"": ""2024-11-21T18:30:00+01:00"", ""end"":...","21 novembre 2024 - 18 décembre 2025, certains ...",2024-11-21T17:30:00+00:00,...,Place de l'Hôtel de Ville 08000 Charleville-Mé...,08000,Charleville-Mézières,Ardennes,Grand Est,NaN,NaN,NaN,False,Titre: Conseil municipal\nDescription: Conseil...
1,1,90172032,https://openagenda.com/villedecmz/events/conco...,Concours de belote,Concours de belote,<p>Début des jeux 20 h 30</p>,NaN,"[{""begin"": ""2025-02-07T19:30:00+01:00"", ""end"":...","Vendredi 7 février 2025, 19h30",2025-02-07T18:30:00+00:00,...,26 bis rue d'Etion 08000 Charleville-Mézières,08000,Charleville-Mézières,Ardennes,Grand Est,NaN,NaN,"[{""type"": ""phone"", ""value"": ""0601715119""}]",False,Titre: Concours de belote\nDescription: Concou...
2,2,257704,https://openagenda.com/villedecmz/events/tourn...,tournoi de ping-pong,ping-pong,NaN,NaN,"[{""begin"": ""2025-01-25T14:00:00+01:00"", ""end"":...",25 et 26 janvier 2025,2025-01-25T13:00:00+00:00,...,14 chemin du Mémorial 08000 Charleville-Mézières,08000,Charleville-Mézières,Ardennes,Grand Est,NaN,NaN,NaN,False,Titre: tournoi de ping-pong\nDescription: ping...
3,3,20351829,https://openagenda.com/villedecmz/events/porte...,Portes ouvertes l'Atelier,l'Atelier,NaN,entrée libre,"[{""begin"": ""2025-01-18T14:00:00+01:00"", ""end"":...","Samedi 18 janvier 2025, 14h00",2025-01-18T13:00:00+00:00,...,3 C rue Louis Hanot 08000 Charleville-Mézières,08000,Charleville-Mézières,Ardennes,Grand Est,NaN,NaN,NaN,False,Titre: Portes ouvertes l'Atelier\nDescription:...
4,4,54005490,https://openagenda.com/villedecmz/events/apres...,Après-midi dansant,Après-midi dansant,NaN,NaN,"[{""begin"": ""2025-01-12T14:00:00+01:00"", ""end"":...","Dimanche 12 janvier 2025, 14h00",2025-01-12T13:00:00+00:00,...,75 avenue Forest 08000 Charleville-Mézières,08000,Charleville-Mézières,Ardennes,Grand Est,NaN,NaN,"[{""type"": ""link"", ""value"": ""https://www.75fore...",False,Titre: Après-midi dansant\nDescription: Après-...

In [22]:
# récupérer les vraies dates de debut et fin de l'évènement
import json
def extract_first_timing(cell):
    if cell is None:
        return None

    # Si c'est une string JSON → on la charge
    if isinstance(cell, str):
        try:
            timings = json.loads(cell)
        except Exception:
            return None
    else:
        # Si c'est déjà une liste Python
        timings = cell

    # si la liste est vide
    if not timings:
        return None, None

    # On prend la première occurrence
    t0 = timings[0]
    return t0.get("begin")

df_verif["begin"] = df_verif["timings"].apply(extract_first_timing)
df_verif["begin"] = pd.to_datetime(df_verif["begin"], utc=True)

In [23]:
df_verif.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11753 entries, 0 to 11752
Data columns (total 23 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Unnamed: 0           11753 non-null  int64
 1   uid                  11753 non-null  int64
 2   canonicalurl         11753 non-null  object
 3   title_fr             11690 non-null  object
 4   description_fr       11690 non-null  object
 5   longdescription_fr   10289 non-null  object
 6   conditions_fr        5922 non-null   object
 7   timings              11753 non-null  object
 8   daterange_fr         11753 non-null  object
 9   firstdate_begin      11753 non-null  object
 10  lastdate_end         11753 non-null  object
 11  location_name        11753 non-null  object
 12  location_address     11753 non-null  object
 13  location_postalcode  11684 non-null  object
 14  location_city        11739 non-null  object
 15  location_department  11753 non-null  object
 16  location_region      11753 non-null  object
 17  age_min              1394 non-null   float64
 18  age_max              2187 non-null   float64
 19  registration         6309 non-null   object
 20  event_actif          11753 non-null  bool
 21  texte_rag            11753 non-null  object
 22  begin                11753 non-null  datetime64[ns, UTC]
dtypes: bool(1), datetime64[ns, UTC](1), float64(2), int64(2), object(17)
memory usage: 2.0+ MB

In [24]:
print(df_verif["begin"].head(20))

0    2024-11-21 17:30:00+00:00
1    2025-02-07 18:30:00+00:00
2    2025-01-25 13:00:00+00:00
3    2025-01-18 13:00:00+00:00
4    2025-01-12 13:00:00+00:00
5    2025-03-12 13:00:00+00:00
6    2025-02-04 17:00:00+00:00
7    2025-03-15 14:00:00+00:00
8    2025-03-16 14:00:00+00:00
9    2025-02-05 08:30:00+00:00
10   2025-03-21 13:00:00+00:00
11   2025-03-22 09:30:00+00:00
12   2025-02-22 09:15:00+00:00
13   2025-01-31 08:15:00+00:00
14   2025-02-05 08:30:00+00:00
15   2025-01-30 17:30:00+00:00
16   2025-01-08 16:00:00+00:00
17   2025-03-19 09:00:00+00:00
18   2025-01-19 15:30:00+00:00
19   2025-03-23 08:00:00+00:00
Name: begin, dtype: datetime64[ns, UTC]

In [32]:

today = pd.Timestamp.now(tz="UTC")
df_26_actuel = df_verif[(df_verif["begin"].dt.year == 2026) & (df_verif["begin"] >= today)]
df_26_actuel.sort_values(by="begin", ascending=True)

df_stras_concert = df_26_actuel[(df_26_actuel['texte_rag'].str.contains('exposition', case=False, na=False)) & (df_verif['location_city'] == 'Strasbourg')]
df_stras_concert

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_17944\1522682918.py:5: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_stras_concert = df_26_actuel[(df_26_actuel['texte_rag'].str.contains('exposition', case=False, na=False)) & (df_verif['location_city'] == 'Strasbourg')]

,Unnamed: 0,uid,canonicalurl,title_fr,description_fr,longdescription_fr,conditions_fr,timings,daterange_fr,firstdate_begin,...,location_postalcode,location_city,location_department,location_region,age_min,age_max,registration,event_actif,texte_rag,begin
9915,9915,9420540,https://openagenda.com/culture/events/visite-t...,"Visite thématique ""L'état sauvage"" au MAMCS",Visite thématique de l’exposition « L’état sau...,<p>Visite thématique de l’exposition « L’état ...,NaN,"[{""begin"": ""2026-09-20T15:30:00+02:00"", ""end"":...","Dimanche 20 septembre, 15h30",2026-09-20T13:30:00+00:00,...,67000,Strasbourg,Bas-Rhin,Grand Est,NaN,NaN,NaN,True,"Titre: Visite thématique ""L'état sauvage"" au M...",2026-09-20 13:30:00+00:00
9997,9997,4541322,https://openagenda.com/culture/events/atelier-...,"Atelier : ""Mobiles de la Cathédrale""",Avec le Collectif Heruditatem.,<p>Avec le Collectif Heruditatem.<br>A partir ...,"RDV au 1er étage du 5e Lieu, dans la salle d'e...","[{""begin"": ""2026-09-19T11:30:00+02:00"", ""end"":...","Samedi 19 septembre, 11h30",2026-09-19T09:30:00+00:00,...,67000,Strasbourg,Bas-Rhin,Grand Est,NaN,NaN,NaN,True,"Titre: Atelier : ""Mobiles de la Cathédrale""\nD...",2026-09-19 09:30:00+00:00
10030,10030,83653324,https://openagenda.com/place-locale/events/ate...,Atelier céramique avec Martha Stahlkopf,L'exposition NUL SOLEIL. MAIS LE FEU d'Alain W...,"<p>Dans les images d’Alain Willaume, la perspe...","30 € par personne – places limitées, inscripti...","[{""begin"": ""2026-08-27T18:00:00+02:00"", ""end"":...","Jeudi 27 août, 18h00",2026-08-27T16:00:00+00:00,...,67000,Strasbourg,Bas-Rhin,Grand Est,NaN,NaN,"[{""type"": ""link"", ""value"": ""https://www.stimul...",True,Titre: Atelier céramique avec Martha Stahlkopf...,2026-08-27 16:00:00+00:00
10261,10261,84147299,https://openagenda.com/culture/events/visite-g...,Visite guidée de l'Hôtel des Postes,Découvrez un des joyaux de la Neustadt : le my...,<p>Découvrez un des joyaux de la Neustadt : le...,Visite guidée gratuite sur inscription. Attent...,"[{""begin"": ""2026-09-19T09:00:00+02:00"", ""end"":...","Samedi 19 septembre, 09h00",2026-09-19T07:00:00+00:00,...,67000,Strasbourg,Collectivité européenne d'Alsace,Grand Est,NaN,NaN,"[{""type"": ""link"", ""value"": ""https://my.weezeve...",True,Titre: Visite guidée de l'Hôtel des Postes\nDe...,2026-09-19 07:00:00+00:00
10299,10299,10300427,https://openagenda.com/culture/events/entre-le...,"Entre les lignes, l'art d'écrire",Dans la continuité de l’exposition « L’écritur...,<p>Dans la continuité de l’exposition «L’écrit...,NaN,"[{""begin"": ""2026-09-19T09:30:00+02:00"", ""end"":...","Samedi 19 septembre, 09h30",2026-09-19T07:30:00+00:00,...,67100,Strasbourg,Collectivité européenne d'Alsace,Grand Est,NaN,NaN,NaN,True,"Titre: Entre les lignes, l'art d'écrire\nDescr...",2026-09-19 07:30:00+00:00
10324,10324,65776428,https://openagenda.com/culture/events/visite-d...,Visite de l'exposition temporaire du Musée Tom...,Visites de l’exposition « À tire-d’aile. Anna ...,<p>Visites de l’exposition « À tire-d’aile. An...,NaN,"[{""begin"": ""2026-09-19T16:30:00+02:00"", ""end"":...",19 et 20 septembre,2026-09-19T14:30:00+00:00,...,67000,Strasbourg,Bas-Rhin,Grand Est,NaN,NaN,NaN,True,Titre: Visite de l'exposition temporaire du Mu...,2026-09-19 14:30:00+00:00
10325,10325,87568950,https://openagenda.com/culture/events/visite-t...,"Visite thématique de l'exposition ""Le temps re...",Visite thématique de l’exposition « Le temps r...,<p>Visite thématique de l’exposition « Le temp...,NaN,"[{""begin"": ""2026-09-20T14:30:00+02:00"", ""end"":...","Dimanche 20 septembre, 14h30",2026-09-20T12:30:00+00:00,...,67000,Strasbourg,Bas-Rhin,Grand Est,NaN,NaN,NaN,True,"Titre: Visite thématique de l'exposition ""Le t...",2026-09-20 12:30:00+00:00
10362,10362,24331278,https://openagenda.com/culture/events/atelier-...,"Atelier : ""Pop-up d'architecture""",Avec Carole Deltenre.,<p>Avec Carole Deltenre.<br>A partir de 4 ans....,"RDV au 1er étage du 5e Lieu, dans la salle d'e...","[{""begin"": ""2026-09-20T14:00:00+02:00"", ""end"":...","Dimanche 20 septembre, 14h00",2026-09-20T12:00:00+00:00,...,67000,Strasbourg,Bas-Rhin,Grand Est,NaN,NaN,NaN,True,"Titre: Atelier : ""Pop-up d'architecture""\nDesc...",2026-09-20 12:00:00+00:00
10400,10400,74446990,https://openagenda.com/culture/events/contes-e...,Contes en famille au Musée zoologique,Contes en famille,"<p>Contes en famille, à partir de 3 ans.<br>Le...",NaN,"[{""begin"": ""2026-09-19T10:00:00+02:00"", ""end"":...","Samedi 19 septembre, 10h00",2026-09-19T08:00:00+00:00,...,67000,Strasbourg,Bas-Rhin,Grand Est,NaN,NaN,NaN,True,Titre: Contes en famille au Musée zoologique\n...,2026-09-19 08:00:00+00:00
10416,10416,6526652,https://openagenda.com/culture/events/mini-exp...,Mini-exposition: les supports de l'image,En complément de la conférence consacrée à l'A...,<p>En complément de la conférence consacrée à ...,NaN,"[{""begin"": ""2026-09-20T14:00:00+02:00"", ""end"":...","Dimanche 20 septembre, 14h00",2026-09-20T12:00:00+00:00,...,67100,Strasbourg,Bas-Rhin,Grand Est,NaN,NaN,NaN,True,Titre: Mini-exposition: les supports de l'imag...,2026-09-20 12:00:00+00:00
10430,10430,4958881,https://openagenda.com/culture/events/visita-l...,Visite libre de l’exposition «Un Voyage à Stra...,"Au 1er étage du 5e Lieu, venez découvrir une e...","<p>Au 1er étage du 5e Lieu, venez découvrir un...",Au 1er étage du 5ème Lieu,"[{""begin"": ""2026-09-19T11:00:00+02:00"", ""end"":...",19 et 20 septembre,2026-09-19T09:00:00+00:00,...,67000,Strasbourg,Bas-Rhin,Grand Est,NaN,NaN,NaN,True,Titre: Visite libre de l’exposition «Un Voyage...,2026-09-19 09:00:00+00:00
10433,10433,81153576,https://openagenda.com/culture/events/100-ans-...,100 ans de Dépôt légal imprimeur à la Bnu,"Il y a 100 ans, la Bnu était instituée bibliot...","<p>Il y a 100 ans, la Bnu était instituée bibl...",Entrée libre,"[{""begin"": ""2026-09-19T10:00:00+02:00"", ""end"":...",19 et 20 septembre,2026-09-19T08:00:00+00:00,...,67000,Strasbourg,Bas-Rhin,Grand Est,NaN,NaN,NaN,True,Titre: 100 ans de Dépôt légal imprimeur à la B...,2026-09-19 08:00:00+00:00
10537,10537,80048901,https://openagenda.com/culture/events/portes-o...,Portes ouvertes : Strasbourg au fil du temps,Partez à la découverte de Strasbourg à travers...,<p>Partez à la découverte de Strasbourg à trav...,NaN,"[{""begin"": ""2026-09-19T10:00:00+02:00"", ""end"":...",19 et 20 septembre,2026-09-19T08:00:00+00:00,...,67100,Strasbourg,Bas-Rhin,Grand Est,NaN,NaN,NaN,True,Titre: Portes ouvertes : Strasbourg au fil du ...,2026-09-19 08:00:00+00:00
10828,10828,6393915,https://openagenda.com/culture/events/visita-g...,"Visite guidée de l'exposition ""Un voyage à Str...",Suivez notre guide pour une visite guidée de l...,<p>Suivez notre guide pour une visite guidée d...,"RDV dans la cour du 5e Lieu, devant l'oriflamme.","[{""begin"": ""2026-09-20T11:30:00+02:00"", ""end"":...","Dimanche 20 septembre, 11h30",2026-09-20T09:30:00+00:00,...,67000,Strasbourg,Bas-Rhin,Grand Est,NaN,NaN,"[{""type"": ""link"", ""value"": ""https://jep26voyag...",True,"Titre: Visite guidée de l'exposition ""Un voyag...",2026-09-20 09:30:00+00:00
10829,10829,5374888,https://openagenda.com/culture/events/martin-l...,Martin Luther King • Droit à la liberté,L’exposition « Martin Luther King – Droit à la...,<p>L’exposition « Martin Luther King – Droit à...,Entrée libre.,"[{""begin"": ""2026-09-19T10:00:00+02:00"", ""end"":...",19 et 20 septembre,2026-09-19T08:00:00+00:00,...,67000,Strasbourg,Bas-Rhin,Grand Est,NaN,NaN,NaN,True,Titre: Martin Luther King • Droit à la liberté...,2026-09-19 08:00:00+00:00
10917,10917,3721539,https://openagenda.com/culture/events/visite-l...,Visite libre du Musée d'Art moderne et contemp...,Visite libre des collections permanentes du Mu...,<p>Visite libre des collections permanentes du...,Gratuit et sans réservation,"[{""begin"": ""2026-09-19T10:00:00+02:00"", ""end"":...",19 et 20 septembre,2026-09-19T08:00:00+00:00,...,67000,Strasbourg,Bas-Rhin,Grand Est,NaN,NaN,NaN,True,Titre: Visite libre du Musée d'Art moderne et ...,2026-09-19 08:00:00+00:00
10962,10962,96550560,https://openagenda.com/culture/events/visite-g...,Visite guidée : Le Patrimoine Mondial de l'UNE...,Partez à la découverte du bien UNESCO étendu a...,<p>Partez à la découverte du bien UNESCO étend...,NaN,"[{""begin"": ""2026-09-19T11:30:00+02:00"", ""end"":...","Samedi 19 septembre, 11h30",2026-09-19T09:30:00+00:00,...,67000,Strasbourg,Bas-Rhin,Grand Est,NaN,NaN,"[{""type"": ""link"", ""value"": ""https://jep26unesc...",True,Titre: Visite guidée : Le Patrimoine Mondial d...,2026-09-19 09:30:00+00:00
11034,11034,19777687,https://openagenda.com/culture/events/museo-de...,Exposition consacrée au parachutisme et aux im...,Découvrez une exposition consacrée au parachut...,<p>Découvrez une exposition consacrée au parac...,Escalier d'accès aux deux salles d'exposition;...,"[{""begin"": ""2026-09-19T10:00:00+02:00"", ""end"":...",19 et 20 septembre,2026-09-19T08:00:00+00:00,...,67100,Strasbourg,Bas-Rhin,Grand Est,NaN,NaN,NaN,True,Titre: Exposition consacrée au parachutisme et...,2026-09-19 08:00:00+00:00
11095,11095,1808309,https://openagenda.com/culture/events/atelier-...,Atelier tout public au MAMCS,"Atelier tout public : « Cours, Eadweard, cours...","<p>Atelier tout public « Cours, Eadweard, cour...",NaN,"[{""begin"": ""2026-09-19T14:30:00+02:00"", ""end"":...","Samedi 19 septembre, 14h30",2026-09-19T12:30:00+00:00,...,67000,Strasbourg,Bas-Rhin,Grand Est,NaN,NaN,NaN,True,Titre: Atelier tout public au MAMCS\nDescripti...,2026-09-19 12:30:00+00:00
11541,11541,42483381,https://openagenda.com/culture/events/a-la-dec...,A la découverte d'une église à pans de bois,Visite libre ou commentée d'une édifice avec e...,<p>Visite libre ou commentée (9h30 et 14h30) d...,NaN,"[{""begin"": ""2026-09-20T09:00:00+02:00"", ""end"":...","Dimanche 20 septembre, 09h00, 14h00",2026-09-20T07:00:00+00:00,...,67200,Strasbourg,Bas-Rhin,Grand Est,NaN,NaN,NaN,True,Titre: A la découverte d'une église à pans de ...,2026-09-20 07:00:00+00:00
11605,11605,59822990,https://openagenda.com/bicentenaire-photograph...,Une photographe révélée Alice Bommer,Une photographe révélée,<h2>Une photographe révélée</h2>\n<h2>Alice Bo...,Entrée libre,"[{""begin"": ""2026-11-07T14:00:00+01:00"", ""end"":...",7 novembre - 23 décembre,2026-11-07T13:00:00+00:00,...,67000,Strasbourg,Bas-Rhin,Grand Est,NaN,NaN,NaN,True,Titre: Une photographe révélée Alice Bommer\nD...,2026-11-07 13:00:00+00:00
11632,11632,5194914,https://openagenda.com/bicentenaire-photograph...,"NEO-ANALOG, une exposition collective","La photographie après l'image, par Evelyne Coh...","<p>La photographie après l'image, par Evelyne ...","Entrée libre du mercredi au samedi, de 14h à 1...","[{""begin"": ""2026-10-09T18:00:00+02:00"", ""end"":...",9 octobre 2026 - 9 janvier 2027,2026-10-09T16:00:00+00:00,...,67000,Strasbourg,Collectivité européenne d'Alsace,Grand Est,NaN,NaN,NaN,True,"Titre: NEO-ANALOG, une exposition collective\n...",2026-10-09 16:00:00+00:00
11721,11721,36722592,https://openagenda.com/saison-mediterranee-202...,Les Faiseuses. Aller-retour Tunis-Strasbourg 2/2,"Porté par El Warcha, le projet Les Faiseuses a...","<p>Porté par El Warcha, le projet Les Faiseuse...",NaN,"[{""begin"": ""2026-10-21T18:00:00+02:00"", ""end"":...",21 - 24 octobre,2026-10-21T16:00:00+00:00,...,67000,Strasbourg,Collectivité européenne d'Alsace,Grand Est,NaN,NaN,"[{""type"": ""link"", ""value"": ""https://my.weezeve...",True,Titre: Les Faiseuses. Aller-retour Tunis-Stras...,2026-10-21 16:00:00+00:00
11730,11730,90089795,https://openagenda.com/bicentenaire-photograph...,Une photographe révélée | Alice Bommer,Texte à venir,"<p>Photographe documentaire et de reportage, A...",NaN,"[{""begin"": ""2026-11-07T14:00:00+01:00"", ""end"":...",7 novembre - 23 décembre,2026-11-07T13:00:00+00:00,...,67000,Strasbourg,Bas-Rhin,Grand Est,NaN,NaN,NaN,True,Titre: Une photographe révélée | Alice Bommer\...,2026-11-07 13:00:00+00:00

In [4]:
df_strasbourg = df_verif[df_verif['location_city'] == 'Strasbourg']
df_strasbourg

,Unnamed: 0,uid,canonicalurl,title_fr,description_fr,longdescription_fr,conditions_fr,timings,daterange_fr,firstdate_begin,...,location_address,location_postalcode,location_city,location_department,location_region,age_min,age_max,registration,event_actif,texte_rag
6,6,79977358,https://openagenda.com/les-evenements-de-la-li...,Rencontre avec Roger Fajnzylberg,Événement gratuit sur inscription via notre si...,<p><strong>Événement gratuit sur inscription</...,NaN,"[{""begin"": ""2025-02-04T18:00:00+01:00"", ""end"":...","Mardi 4 février 2025, 18h00",2025-02-04T17:00:00+00:00,...,"1 rue des Francs Bourgeois,Strasbourg",67000,Strasbourg,Bas-Rhin,Grand Est,NaN,NaN,"[{""type"": ""link"", ""value"": ""https://www.eventb...",False,Titre: Rencontre avec Roger Fajnzylberg\nDescr...
19,19,9596870,https://openagenda.com/unidivers-oui-sortir/ev...,RETRO GAM’IN - STRASBOURG,Evènement RETRO GAM'IN - STRASBOURG 2025 le di...,<p>Ne manquez pas l'Evènement RETRO GAM'IN - S...,sur inscription par mail a partir de 15€ le m ...,"[{""begin"": ""2025-03-23T09:00:00+01:00"", ""end"":...","Dimanche 23 mars 2025, 09h00",2025-03-23T08:00:00+00:00,...,67100,67100,Strasbourg,Bas-Rhin,Grand Est,NaN,99.0,"[{""type"": ""email"", ""value"": ""tandem.events71@g...",False,Titre: RETRO GAM’IN - STRASBOURG\nDescription:...
23,23,64666218,https://openagenda.com/les-evenements-de-la-li...,Rencontre avec Roland Gori,Événement gratuit sur inscription via notre si...,<p><strong>Événement gratuit sur inscription</...,NaN,"[{""begin"": ""2025-03-07T17:30:00+01:00"", ""end"":...","Vendredi 7 mars 2025, 17h30",2025-03-07T16:30:00+00:00,...,"1 rue des Francs Bourgeois,Strasbourg",67000,Strasbourg,Bas-Rhin,Grand Est,NaN,NaN,"[{""type"": ""link"", ""value"": ""https://www.eventb...",False,Titre: Rencontre avec Roland Gori\nDescription...
42,42,36795759,https://openagenda.com/les-evenements-de-la-li...,Rencontre avec Marta Caraion,Événement gratuit sur inscription via notre si...,<p><strong>Événement gratuit sur inscription</...,NaN,"[{""begin"": ""2025-03-04T17:00:00+01:00"", ""end"":...","Mardi 4 mars 2025, 17h00",2025-03-04T16:00:00+00:00,...,"1 rue des Francs Bourgeois,Strasbourg",67000,Strasbourg,Bas-Rhin,Grand Est,NaN,NaN,"[{""type"": ""link"", ""value"": ""https://www.eventb...",False,Titre: Rencontre avec Marta Caraion\nDescripti...
54,54,40996137,https://openagenda.com/les-evenements-de-la-li...,Rencontre avec Marie Nimier,Événement gratuit sur inscription via notre si...,<p><strong>Événement gratuit sur inscription</...,NaN,"[{""begin"": ""2025-02-12T18:00:00+01:00"", ""end"":...","Mercredi 12 février 2025, 18h00",2025-02-12T17:00:00+00:00,...,"1 rue des Francs Bourgeois,Strasbourg",67000,Strasbourg,Bas-Rhin,Grand Est,NaN,NaN,"[{""type"": ""link"", ""value"": ""https://www.eventb...",False,Titre: Rencontre avec Marie Nimier\nDescriptio...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11673,11673,84772811,https://openagenda.com/bicentenaire-photograph...,En quête des photographies d'Alice Bommer,Informations à venir,<p>Informations à venir<br>Le vernissage le 06...,NaN,"[{""begin"": ""2026-11-06T18:00:00+01:00"", ""end"":...",6 novembre - 25 décembre,2026-11-06T17:00:00+00:00,...,"4 Place d'Austerlitz, 67000 Strasbourg, France",67000,Strasbourg,Bas-Rhin,Grand Est,NaN,NaN,NaN,True,Titre: En quête des photographies d'Alice Bomm...
11682,11682,66227214,https://openagenda.com/culture/events/200-sole...,200 soleils : collecte de photographies,Biblis en folie 2026,"<p>Cette année, la photographie fête ses 200 a...",NaN,"[{""begin"": ""2026-10-03T14:00:00+02:00"", ""end"":...","Samedi 3 octobre, 14h00",2026-10-03T12:00:00+00:00,...,"3 Rue Kuhn, 67000 Strasbourg, France",67000,Strasbourg,Bas-Rhin,Grand Est,NaN,NaN,NaN,True,Titre: 200 soleils : collecte de photographies...
11721,11721,36722592,https://openagenda.com/saison-mediterranee-202...,Les Faiseuses. Aller-retour Tunis-Strasbourg 2/2,"Porté par El Warcha, le projet Les Faiseuses a...","<p>Porté par El Warcha, le projet Les Faiseuse...",NaN,"[{""begin"": ""2026-10-21T18:00:00+02:00"", ""end"":...",21 - 24 octobre,2026-10-21T16:00:00+00:00,...,"1, rue de l'Académie 67000 Strasbourg",67000,Strasbourg,Collectivité européenne d'Alsace,Grand Est,NaN,NaN,"[{""type"": ""link"", ""value"": ""https://my.weezeve...",True,Titre: Les Faiseuses. Aller-retour Tunis-Stras...
11725,11725,46629009,https://openagenda.com/panthea/events/thesee-s...,"THÉSÉE, SA VIE NOUVELLE l Valérie Dréville et ...",audiodescription sur casque audio,"<p>Thésée part s’installer à Berlin, la « Vill...",Prix du billet,"[{""begin"": ""2026-10-14T20:30:00+02:00"", ""end"":...","Mercredi 14 octobre, 20h30",2026-10-14T18:30:00+00:00,...,"1 boulevard de Dresde, 67000 Strasbourg",67000,Strasbourg,Collectivité européenne d'Alsace,Grand Est,14.0,99.0,"[{""type"": ""email"", ""value"": ""mathis.bruneteaux...",True,"Titre: THÉSÉE, SA VIE NOUVELLE l Valérie Drévi..."
11730,11730,90089795,https://openagenda.com/bicentenaire-photograph...,Une photographe révélée | Alice Bommer,Texte à venir,"<p>Photographe documentaire et de reportage, A...",NaN,"[{""begin"": ""2026-11-07T14:00:00+01:00"", ""end"":...",7 novembre - 23 décembre,2026-11-07T13:00:00+00:00,...,"4 Place d'Austerlitz, 67000 Strasbourg, France",67000,Strasbourg,Bas-Rhin,Grand Est,NaN,NaN,NaN,True,Titre: Une photographe révélée | Alice Bommer\...

In [ ]:
df_strasbourg_26 =

In [6]:
max(df_verif["firstdate_begin"])

'2026-12-19T14:00:00+00:00'

In [7]:
min(df_verif["firstdate_begin"])

'2025-01-01T18:00:00+00:00'

In [8]:
max(df_verif["lastdate_end"])

'2043-06-04T12:00:00+00:00'

In [ ]:
min(df_verif["lastdate_end"])

'2025-01-04T16:30:00+00:00'

In [11]:
df_verif['location_city'].unique()

<ArrowStringArray>
['Charleville-Mézières',           'Strasbourg',    'Villers-lès-Nancy',
           'Lapoutroie',                'Laxou',               'Colmar',
            'Fellering',    'Sainte-Marguerite',                'Reims',
                'NANCY',
 ...
   'Brienne-la-Vieille',          'Fromelennes',          'Saint-Oulph',
           'Ortoncourt',         'Willgottheim',        'Pierrevillers',
      'Montigny le Roi',             'Distroff',                'Lesse',
     'Bourgogne-Fresne']
Length: 1391, dtype: str

In [38]:

results_df = pd.read_csv("ragas_results.csv")
results_df["answer_relevancy"].value_counts()

Series([], Name: count, dtype: int64)

In [36]:
results_df.columns

Index(['user_input', 'retrieved_contexts', 'response', 'reference',
       'faithfulness', 'answer_relevancy', 'context_precision',
       'context_recall'],
      dtype='object')

In [37]:
results_df

,user_input,retrieved_contexts,response,reference,faithfulness,answer_relevancy,context_precision,context_recall
0,Je cherche un atelier pour un enfant à Reims.,['Titre: Ateliers culinaires pour enfants à la...,Voici une sélection d’ateliers à Reims adaptés...,"À Reims, trois ateliers sont adaptés aux enfan...",NaN,NaN,NaN,NaN
1,Quels événements sont prévus ce week-end à Str...,['<p>Chaque parcours vous plonge dans une hist...,Voici les événements prévus **ce week-end à St...,"Ce week-end à Strasbourg, les activités princi...",NaN,NaN,NaN,NaN
2,Y a-t-il des concerts gratuits à Metz?,[],Voici quelques concerts gratuits à Metz ou dan...,"À Metz, il y a deux concerts gratuits : un con...",NaN,NaN,0.0,0.0
3,Quels événements sont adaptés aux seniors à Na...,['Age minimum: nan\nAge maximum: nan\nVille: N...,Voici une sélection d'événements culturels à N...,"À Nancy, trois activités conviennent aux senio...",NaN,NaN,NaN,NaN
4,Que faire en famille à Mulhouse demain?,['Adresse: 16 rue de la Fonderie 68100 Mulhous...,Voici les événements familiaux prévus **demain...,"À Mulhouse, trois activités familiales sont pr...",NaN,NaN,NaN,NaN
5,Je cherche des ateliers créatifs à Champagne e...,"[""Titre: Atelier ludique et créatif\nDescripti...",Voici les événements les plus pertinents pour ...,À Charleville-Mézières et dans la région de Ch...,0.26,NaN,0.0,0.0